### ISSUE TITLE
Kismet does not receive any data

### ISSUE THREAD

**Issue by OP-drone** [alphafox02/SniffleToKismet#1]
Sonoff Zigbee 3.0 USB Dongle Plus ( CC2652P )

FW sniffle_cc1352p1_cc2652p1_1M.hex ( Version 1.10.0 ) @ https://github.com/nccgroup/Sniffle/

Sniffle branch OpenDroneID @ https://github.com/bkerler/Sniffle

GPS received

Mavic 3 ,mavic mini 3 pro ( latest fw )

Drone APP = Remote ID functionality normal

Kismet build from source

**Comment by alphafox02** [comment]
The Mavic three only does Wi-Fi type remote ID not Bluetooth. Sniffle is for Bluetooth, specifically I’ve been detecting Bluetooth long range as Bluetooth legacy wouldn’t be too much of importance to me.

**Comment by alphafox02** [comment]
The drone app can use or detect Wi-Fi or Bluetooth using your phones hardware. I suspect if you look probably into it more that you were only receiving the Wi-Fi type remote ID. If I’m wrong, please let me know so I can look into it more.

**Comment by OP-drone** [comment]
After numerous checks I found out that Mavic only sends Wi-Fi RID packets.

**Comment by alphafox02** [comment]
What a bummer! But good that you were able to confirm that. I thought for sure I had heard it was only Wi-Fi.

**Comment by OP-drone** [comment]
Wi-Fi RID is implemented not only on Mavic other manufacturers also use it, Wi-Fi RID support is needed.

**Comment by alphafox02** [comment]
Totally agree, but keep in mind Sniffle is BT only. So I’ll have to look at some other way or add in something else to assist. I’m assuming it’s only a matter of time before kismet officially rolls in something. I’ll reach out to see.

**Comment by alphafox02** [comment]
There’s a new technique to detect the WiFi type. I’ll get you details this evening.
